version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  mediscreen:
    depends_on:
      - mysqldb
    image: mediscreen-patient:latest
    container_name: mediscreen-patient
    build:
      context: ./mediscreen
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - 8081:8080

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mediscreen?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      volumes:
         -/my/project/dir:/app
      stdin_open: true
      tty: true

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  note:
    depends_on:
      - mongodb
    image: mediscreen-note:latest
    container_name: mediscreen-note
    ports:
      - "8082:8082"
    networks:
      - default
    environment:
      - "spring_data_mongodb_host=mongodb"
      # - "front.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://mediscreen-rapport:8083"

  rapport:
    image: mediscreen-rapport:latest
    container_name: mediscreen-rapport
    ports:
      - "8083:8083"
    networks:
      - default
    environment:
      # - "front.serviceUrl=http://localhost"
      - "patient.serviceUrl=http://mediscreen:8081"
      - "note.serviceUrl=http://mediscreen-note:8082"

  front:
    image: mediscreen-front:latest
    container_name: mediscreen-front
    build:
      context: ./mediscreen-front
      dockerfile: Dockerfile
    environment:
      - mediscreen
      - mediscreen-note
      - mediscreen-rapport
    ports:
      - 8080:8080
    networks:
      - default
    restart: always

volumes:
  db:
  mongodb_data_container:
