version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediscreen
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  mediscreen:
    depends_on:
      - mysqldb
    image: mediscreen-patient:latest
    container_name: mediscreen-patient
    build: ./Mediscreen
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      volumes:
         .m2:/root/.m2
      stdin_open: true
      tty: true

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  note:
    depends_on:
      - mongodb
    image: mediscreen-note:latest
    container_name: mediscreen-note
    ports:
      - "8082:8082"
    networks:
      - default
    environment:
      - "spring_data_mongodb_host=mongodb"
      # - "front.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://mediscreen-rapport:8083"

  rapport:
    image: mediscreen-rapport:latest
    container_name: mediscreen-rapport
    ports:
      - "8083:8083"
    networks:
      - default
    environment:
      # - "front.serviceUrl=http://localhost"
      - "patient.serviceUrl=http://mediscreen:8081"
      - "note.serviceUrl=http://mediscreen-note:8082"

volumes:
  db:
  mongodb_data_container:
