version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  patient:
    depends_on:
      - mysql
    image: mediscreen-patient
    container_name: mediscreen-patient
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - "spring_datasource_username=root"
      - "spring_datasource_password=root"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/mediscreen?serverTimezone=UTC"
     # - "front.serviceUrl=http://localhost"
      - "note.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://localhost://mediscreen-rapport:8083"

  notes:
    depends_on:
      - mongodb
    image: mediscreen-note
    container_name: mediscreen-note
    ports:
      - "8082:8082"
    networks:
      - default
    environment:
      - "spring_data_mongodb_host=mongodb"
     # - "front.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://mediscreen-rapport:8083"

  rapport:
    image: mediscreen-rapport
    container_name: mediscreen-rapport
    ports:
      - "8083:8083"
    networks:
      - default
    environment:
     # - "front.serviceUrl=http://localhost"
      - "patient.serviceUrl=http://mediscreen-patient:8081"
      - "note.serviceUrl=http://mediscreen-note:8082"



volumes:
  mysql_db_data_container:
  mongodb_data_container:
