version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediscreen
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mediscreen:
    depends_on:
      - mysql
    image: mediscreen-patient:latest
    container_name: mediscreen-patient
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - "spring_datasource_username=root"
      - "spring_datasource_password=root"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/mediscreen?autoReconnect=true&useSSL=false"
      # - "front.serviceUrl=http://localhost"
      - "note.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://localhost://mediscreen-rapport:8083"

  note:
    depends_on:
      - mongodb
    image: mediscreen-note:latest
    container_name: mediscreen-note
    ports:
      - "8082:8082"
    networks:
      - default
    environment:
      - "spring_data_mongodb_host=mongodb"
      # - "front.serviceUrl=http://localhost"
      - "rapport.serviceUrl=http://mediscreen-rapport:8083"

  rapport:
    image: mediscreen-rapport:latest
    container_name: mediscreen-rapport
    ports:
      - "8083:8083"
    networks:
      - default
    environment:
      # - "front.serviceUrl=http://localhost"
      - "patient.serviceUrl=http://mediscreen:8081"
      - "note.serviceUrl=http://mediscreen-note:8082"

volumes:
  mysql_db_data_container:
  mongodb_data_container:
